"""add user timezone

Revision ID: 0a0d9c1e52eb
Revises: 85c3bb29efee
Create Date: 2026-08-17 09:55:44.898637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0d9c1e52eb'
down_revision: Union[str, Sequence[str], None] = '85c3bb29efee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "timezone",
            sa.String(length=100),
            nullable=False,
            server_default="America/New_York",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
