"""add stock tracking fields

Revision ID: 85c3bb29efee
Revises: 0377cfe7512e
Create Date: 2026-08-17 08:59:07.983672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c3bb29efee'
down_revision: Union[str, Sequence[str], None] = '0377cfe7512e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_products', sa.Column('is_in_stock', sa.Boolean(), nullable=True))
    op.add_column('tracked_products', sa.Column('last_stock_alert_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_products', 'last_stock_alert_at')
    op.drop_column('tracked_products', 'is_in_stock')
    # ### end Alembic commands ###
